package com.emwa.model;
// Generated Feb 27, 2020 12:51:18 AM by Hibernate Tools 5.1.10.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import com.fasterxml.jackson.annotation.JsonManagedReference;

/**
 * Depart generated by hbm2java
 */
@Entity
@Table(name = "depart", catalog = "employeemanager")
public class Depart implements java.io.Serializable {

	private Long departId;
	private String departName;
	private String description;
	private Set<Staff> staffs = new HashSet<Staff>(0);

	public Depart() {
	}

	public Depart(String departName, String description) {
		this.departName = departName;
		this.description = description;
	}

	public Depart(String departName, String description, Set<Staff> staffs) {
		this.departName = departName;
		this.description = description;
		this.staffs = staffs;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "depart_id", unique = true, nullable = false)
	public Long getDepartId() {
		return this.departId;
	}

	public void setDepartId(Long departId) {
		this.departId = departId;
	}

	@Column(name = "depart_name", nullable = false, length = 250)
	public String getDepartName() {
		return this.departName;
	}

	public void setDepartName(String departName) {
		this.departName = departName;
	}

	@Column(name = "description", nullable = false, length = 250)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "depart")
	@JsonManagedReference
	public Set<Staff> getStaffs() {
		return this.staffs;
	}

	public void setStaffs(Set<Staff> staffs) {
		this.staffs = staffs;
	}

}
